Repository Team-MBTI/frontend, pull requests merged in 2023-07, with the labels that each got.

#7 Feat/mbti test page
  .eslintrc.json
  public/svg/back.svg
  public/svg/check.svg
  src/components/common/ProgressBar.tsx
  src/components/common/ToastMessage/ToastMessage.style.ts
  src/components/common/ToastMessage/index.tsx
  src/components/test/index.style.ts
  src/hooks/useMBTITest.ts
  src/pages/_app.tsx
  src/pages/test/[id]/index.tsx
  src/store/GlobalStore.ts
  src/styles/theme.ts
  tsconfig.json
Labels: enhancement

#8 feat: Layout Component complete
  src/components/common/Layout/Layout.style.ts
  src/components/common/Layout/index.tsx
  src/pages/_app.tsx
Labels: FE

#10 feat: button component ing..
  .eslintrc.json
  public/images/kakao_login_large_narrow.png
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.style.ts
  src/components/common/Button/index.tsx
  src/pages/index.tsx
Labels: FE

#13 🚧 Input Component Complete.
  public/svg/ic-textfield-success-24.svg
  public/svg/ic-textfielderror-24.svg
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.style.ts
  src/components/common/Input/index.tsx
  src/interfaces/input.ts
Labels: FE

#15 ♻️: add Button Props (onClick, className)
  src/components/common/Button/Button.style.ts
  src/components/common/Button/index.tsx
Labels: FE

#18 ♻️: Input Component stylebyStatus func modify, reset bg color #fff apply
  src/components/common/Input/Input.style.ts
  src/styles/reset.css
Labels: FE

#21 🚧 Result Page UI complete.
  public/img/kakaoCopy.png
  public/img/linkCopy.png
  src/components/Modal/ThemeModal.style.tsx
  src/components/Modal/ThemeModal.tsx
  src/components/result/index.style.ts
  src/hooks/useCopyClipBoard.tsx
  src/pages/result/index.tsx
Labels: FE, feature

#19 🚧 Login Page UI complete.
  .eslintrc.json
  next.config.js
  package.json
  src/apis/testApi.ts
  src/components/common/Input/index.tsx
  src/env/.env.example
  src/pages/_document.tsx
  src/pages/login/Login.style.ts
  src/pages/login/index.tsx
  src/utils/cookie.ts
  yarn.lock
Labels: FE

#23 refac/button merge to FE
  .github/ISSUE_TEMPLATE/feature_request.md
  src/components/common/Button/Button.style.ts
  src/components/common/Button/index.tsx
Labels: FE

#33 🚧 feature/loading-spinner ing ..
  src/components/common/LoadingSpinner.tsx
  src/components/common/LoadingSpinner/index.tsx
Labels: FE

#34 🚧 feat: Main Page & Test Question Page api connect complete.
  .eslintrc.json
  src/apis/travel.ts
  src/components/ShareBox/index.tsx
  src/components/test/index.style.ts
  src/constants/mbti.ts
  src/hooks/useMBTITest.ts
  src/interfaces/travel.ts
  src/pages/main/index.tsx
  src/pages/test/[id]/index.tsx
Labels: FE

#36 🚧 feat: resultPage data binding complete.
  next.config.js
  src/components/ShareBox/index.tsx
  src/hooks/useCopyClipBoard.tsx
  src/pages/_app.tsx
  src/pages/result/Result.style.ts
  src/pages/result/index.tsx
Labels: FE

#40 FE branch merge to dev
  .eslintrc.json
  next.config.js
  public/images/close.png
  public/images/kakaoCopy.png
  public/images/linkCopy.png
  src/apis/travel.ts
  src/components/Modal/ThemeModal.style.tsx
  src/components/Modal/ThemeModal.tsx
  src/components/ShareBox/ShareBox.style.ts
  src/components/ShareBox/index.tsx
  src/components/common/Layout/index.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/LoadingSpinner/index.tsx
  src/components/test/index.style.ts
  src/constants/mbti.ts
  src/hooks/useCopyClipBoard.tsx
  src/hooks/useMBTITest.ts
  src/interfaces/travel.ts
  src/pages/_app.tsx
  src/pages/login/Login.style.ts
  src/pages/login/index.tsx
  src/pages/main/Main.style.ts
  src/pages/main/index.tsx
  src/pages/result/Result.style.ts
  src/pages/result/index.tsx
  src/pages/test/[id]/index.tsx
  src/store/GlobalStore.ts
  src/styles/reset.css
Labels: FE
